# Generated by Django 4.0.2 on 2022-03-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroup',
            name='supervisor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitydetail',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_details', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='supervisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='entities.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='entities.entity'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('name',), name='Unique Entity Name'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('entity', 'name')},
        ),
    ]
