# Generated by Django 4.0.3 on 2022-04-27 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('not sent', 'not sent'), ('sent', 'sent'), ('OK', 'OK'), ('NOK', 'NOK')], default='not sent', editable=False, max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status')),
                ('sent_on', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status', when={'sent'})),
                ('confirmed_on', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status', when={'NOK', 'OK'})),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'partnerships',
            },
        ),
        migrations.RemoveField(
            model_name='entitygroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='entitygroup',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='entitygroupmember',
            name='entity_group',
        ),
        migrations.RemoveField(
            model_name='entitygroupmember',
            name='entity_member',
        ),
        migrations.RemoveConstraint(
            model_name='entity',
            name='Unique Entity Name',
        ),
        migrations.AddField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='entities.entity'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_entity_name'),
        ),
        migrations.DeleteModel(
            name='EntityGroup',
        ),
        migrations.DeleteModel(
            name='EntityGroupMember',
        ),
        migrations.AddField(
            model_name='partnership',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity'),
        ),
    ]
